name: Feature / Enhancement
description: Propose a new feature or major enhancement
title: "[Feature] "
labels: ["enhancement"]
body:
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: What is being proposed?
    validations:
      required: true

  - type: textarea
    id: rationale
    attributes:
      label: Rationale
      description: Why does Embers need this?
    validations:
      required: true

  - type: dropdown
    id: risk
    attributes:
      label: Risk Level
      options:
        - Low
        - Medium
        - High
    validations:
      required: true

  - type: textarea
    id: tasks
    attributes:
      label: Task Breakdown
      description: Provide phased tasks and test gates
